title: ""
author: ""
copyright: "2020"
logo: content/images/climate_estimate_logo.png 

latex:
  latex_engine: pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'

repository:
  url: https://github.com/atrisovic/weather-panel.github.io/ 
  branch: master
  path_to_book: tutorial-content

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  favicon: content/images/favicon.png
  extra_footer: |
    <p>
    &copy; 2020 - This work is licensed under CC-BY-SA-4.0 <br>
    </p>
sphinx:
  config:
    html_show_copyright: false

parse:
  myst_enable_extensions:
    - amsmath
    - html_image
    - dollarmath
    - colon_fence
    - deflist
    - html_admonition
    - linkify
    - replacements
    - smartquotes
    - substitution

execute:
  execute_notebooks: "off"
