title: ""
author: ""
copyright: "2020"
logo: content/images/climate_estimate_logo.png 

latex:
  latex_engine: pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'

repository:
  url: https://github.com/atrisovic/weather-panel.github.io/ 
  branch: master
  path_to_book: tutorial-content

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  favicon: content/images/favicon.png

parse:
  myst_extended_syntax: true

execute:
  execute_notebooks: "off"
