name: CI

on:
  push:
    branches:
    - master
      
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: Run a build
      run: |
        pip install jupyter-book
        jupyter-book build ./weather-panel.github.io
