name: deploy-book 

on: 
  push:
    branches:
      - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11 
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build Jupyter Book 
      run: |
        jupyter-book build tutorial-content/ 

    - name: Add Redirect
      run: |
        cd ./tutorial-content/_build/html
        echo '<html><head><meta http-equiv="Refresh" content="0; url=https://climateestimate.net/content/getting-started.html"></head><body><p>Page has moved to <a href="https://climateestimate.net/content/getting-started.html">https://climateestimate.net/content/getting-started.html</a></p></body></html>' > getting-started.html

    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./tutorial-content/_build/html
        cname: climateestimate.net
